# Generated by Django 5.0.7 on 2024-09-20 03:17

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('super_admin', 'Super Admin')], max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255, unique=True)),
                ('dept_code', models.CharField(max_length=255, unique=True)),
                ('dept_location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dept_contact_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('Ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=20)),
                ('Issue_Caption', models.CharField(default='Screen Issue', max_length=50)),
                ('Issue_Description', models.TextField()),
                ('Priority', models.CharField(default='low', max_length=20)),
                ('Status', models.CharField(default='Open', max_length=20)),
                ('Assigned_to', models.CharField(blank=True, max_length=50)),
                ('Comments', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Last_Updated_Date', models.DateField(auto_now=True)),
                ('Resolution_date', models.DateField(blank=True, null=True)),
                ('Issue_ScreenShot', models.FileField(blank=True, upload_to=api.models.issue_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_uid', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('specialization', models.CharField(max_length=50)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('status', models.CharField(default='Active', max_length=15)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'receptionist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
