# Generated by Django 5.0.7 on 2024-08-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ststus',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
