# Generated by Django 5.0.7 on 2024-12-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_dob_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reffered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
