# Generated by Django 5.0.7 on 2024-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_admin_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='joined_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
