# Generated by Django 5.0.7 on 2024-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_coontact_no_patient_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Patient', 'Patient')], max_length=50),
        ),
    ]
