# Generated by Django 5.0.7 on 2025-01-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_reffered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
