# Generated by Django 5.0.7 on 2024-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_doctor_joined_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
