# Generated by Django 5.0.7 on 2024-08-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ststus',
            new_name='status',
        ),
    ]
