# Generated by Django 5.0.7 on 2024-08-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ststus_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('super_admin', 'Super Admin')], max_length=20, null=True),
        ),
    ]
