# Generated by Django 5.0.7 on 2024-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_receptionist_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dept_id',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_uid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
