# Generated by Django 5.0.7 on 2024-08-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
    ]
