# Generated by Django 5.0.7 on 2024-08-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_patient_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.AlterField(
            model_name='patient',
            name='joined_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
