# Generated by Django 5.0.7 on 2024-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctor_status_receptionist_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('Ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=20)),
                ('Issue_Caption', models.CharField(max_length=50)),
                ('Issue_Description', models.TextField()),
                ('Priority', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('Assigned_to', models.CharField(max_length=50)),
                ('Comments', models.TextField()),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Last_Updated_Date', models.DateField(auto_now=True)),
                ('Resolution_date', models.DateField()),
                ('Issue_ScreenShot', models.ImageField(upload_to='support/')),
            ],
        ),
    ]
