# Generated by Django 5.0.7 on 2024-08-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_patient_password_alter_patient_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
