# Generated by Django 5.0.7 on 2024-08-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_patient_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
