# Generated by Django 5.0.7 on 2024-08-31 02:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_support_issue_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='Assigned_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='Comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='Issue_ScreenShot',
            field=models.FileField(blank=True, upload_to=api.models.issue_upload_to),
        ),
        migrations.AlterField(
            model_name='support',
            name='Resolution_date',
            field=models.DateField(blank=True),
        ),
    ]
