# Generated by Django 5.0.7 on 2024-08-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_support_assigned_to_alter_support_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='Resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
