# Generated by Django 5.0.7 on 2024-08-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_patient_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
