# Generated by Django 5.0.7 on 2024-08-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
