# Generated by Django 5.0.7 on 2024-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customuser_id_alter_doctor_id_alter_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('super_admin', 'Super Admin')], max_length=20),
        ),
    ]
