# Generated by Django 5.0.7 on 2024-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_department_dept_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
