# Generated by Django 5.0.7 on 2024-08-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/report_files/'),
        ),
    ]
