# Generated by Django 5.0.7 on 2024-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_test_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_contact',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
