# Generated by Django 5.0.7 on 2024-08-19 12:15

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_report_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, upload_to=services.models.report_upload_to),
        ),
    ]
