# Generated by Django 5.0.7 on 2024-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
