# Generated by Django 5.0.7 on 2024-08-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('services', '0003_alter_report_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='HospitalVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patiend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient', to_field='uuid')),
            ],
        ),
    ]
