# Generated by Django 5.0.7 on 2024-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_prescription_date_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
