# Generated by Django 5.0.7 on 2024-08-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_appointment_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
