# Generated by Django 5.0.7 on 2024-08-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_test_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
