# Generated by Django 5.0.7 on 2024-08-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_test_test_code_alter_test_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription_files',
            new_name='prescription_file',
        ),
    ]
