# Generated by Django 5.0.7 on 2024-09-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_rename_messege_prescription_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalVisitLog',
        ),
    ]
