# Generated by Django 5.0.7 on 2024-09-01 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_delete_hospitalvisitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='appointment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='services.appointment'),
        ),
    ]
