# Generated by Django 5.0.7 on 2024-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_appointment_id_alter_prescription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='advice',
            field=models.TextField(blank=True),
        ),
    ]
