# Generated by Django 5.0.7 on 2024-09-02 16:57

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_appointment_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, upload_to=services.models.prescription_upload_to),
        ),
    ]
