# Generated by Django 5.0.7 on 2024-09-02 18:19

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_prescription_prescription_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(upload_to=services.models.prescription_upload_to),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to=services.models.report_upload_to),
        ),
    ]
