# Generated by Django 5.0.7 on 2024-09-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_prescription_prescription_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('Test', 'Test'), ('Diagnostic', 'Diagnostic')], max_length=100),
        ),
    ]
